apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-app
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/MANIKANDAN242221/Sample-java-spring-app.git
    targetRevision: main
    path: argocd-manifest  # folder where your deployment.yaml is
  project: default
  syncPolicy:
    automated:
      prune: true      # delete old resources not in git
      selfHeal: true   # fix drift automatically
    syncOptions:
    - CreateNamespace=true
